//pulled from https://remotive.com/api/remote-jobs?search=javascript

module.exports =[
{
id: 1224255,
url: "https://remotive.com/remote-jobs/software-dev/full-stack-engineer-customer-solutions-team-1224255",
title: "Full Stack Engineer - Customer Solutions Team",
company_name: "Discourse",
company_logo: "https://remotive.com/job/1224255/logo",
category: "Software Development",
tags: [
"developer",
"javascript",
"rails",
"ruby",
"customer success",
"product",
"people",
"plugins",
"communication"
],
job_type: "full_time",
publication_date: "2022-07-04T17:31:22",
candidate_required_location: "Worldwide",
salary: "",
description: `<div class="h5"><em>Salary dependent on location and experience</em></div> <p class="h1"> </p> <p class="h1"><!--block-->About the job</p> <p>You will work closely with some of Discourse’s largest clients to help them with their extensive customizations. You will also be contributing to Discourse’s core product and official plugins.</p> <p><!--block--><br>Responsibilities include:<br><br></p> <ul> <li><!--block-->Communicate daily with clients and work with them to agree on work priorities</li> <li><!--block-->Implement and document client features</li> <li><!--block-->Discuss and decide with internal Discourse teams whether features are appropriate in core, or in client plugins</li> <li><!--block-->Maintain client-specific features against latest core versions</li> <li><!--block-->Highlight new critical core features to high-profile clients</li> <li><!--block-->Schedule and deploy patches and upgrades</li> </ul> <p><!--block--><br><strong>About you</strong></p> <p><!--block--></p> <ul> <li>You are an experienced full stack developer who has an interest in proposing and providing direct solutions to aid in customer success. You have excellent written and verbal communication skills and are comfortable working in a fully remote team.</li> <li>You should be excited about customizing open-source solutions to fit a customer’s requirements.</li> <li>You have Ruby, Rails and JavaScript experience; Discourse applicants usually complete a paid trial project prior to joining the team.</li> <li>You should be kind to your co-workers. We believe in a welcoming workplace where people from different backgrounds and cultures work together to create something great.</li> </ul> <p> </p> <p><!--block--><br><strong>About us</strong><br><br></p> <p>There are many benefits to working at Discourse including a flexible work schedule, 5 weeks of holiday per year, funding for a co-working space, and more! <a href="https://www.discourse.org/team#benefits" rel="nofollow">Learn more</a>.<br><br></p> <p><!--block--><br><strong>How to Apply</strong></p> <p><!--block--><br>Please send a detailed cover letter along with your resume to <a href="mailto:jobs+wwr@discourse.org" rel="nofollow">jobs+wwr@discourse.org</a><br><br></p> <!--block--> <p><br><br></p> <img src="https://remotive.com/job/track/1224255/blank.gif?source=public_api" alt=""/>`,
company_logo_url: "https://remotive.com/job/1224255/logo"
},
{
id: 1288644,
url: "https://remotive.com/remote-jobs/software-dev/senior-software-developer-tech-lead-1288644",
title: "Senior Software Developer & Tech Lead",
company_name: "Jobiqo1",
company_logo: "https://remotive.com/job/1288644/logo",
category: "Software Development",
tags: [
"apache",
"customer support",
"developer",
"drupal",
"education",
"javascript",
"mySQL",
"php",
"saas",
"scrum",
"open source",
"management",
"ai",
"agile",
"customer success",
"research",
"documentation",
"product",
"HTML5",
"css3",
"knowledge",
"mentoring",
"recruiting",
"coaching",
"German",
"English",
"software development",
"infrastructure",
"leadership",
"React.js",
"SOLID",
"events",
"architect",
"development",
"IT",
"implementation",
"testing",
"next.js",
"communication",
"time management",
"support",
"diversity",
"software",
"training"
],
job_type: "full_time",
publication_date: "2022-07-04T11:39:40",
candidate_required_location: "Europe",
salary: "",
description: `<div class="h3" dir="ltr"><strong>About Us</strong></div> <p dir="ltr">Jobiqo provides the next generation job board software and AI-enabled matching technology combining both the benefits of a scalable SaaS platform and the flexibility of a custom solution. We help global publishers, local newspapers, educational institutions, and anyone that owns job boards to reach a new level of quality and professionalism in online recruiting with our technology. With more than 100+ customers in 20+ markets globally, we have grown to be the leading job board software provider worldwide.</p> <p dir="ltr">Our growing team works from offices in Vienna, Bratislava and London or remotely. We share values around diversity, flexibility, responsibility and are contributing to open source projects</p> <p dir="ltr">As a Senior Software Developer &amp; Tech Lead you plan and shape product improvements and client requests from a technical perspective as well as develop software and contribute to our product. You work closely with other Developers, Product Owners, Customer Success Managers and Customer Support Specialists in an agile setup (SCRUM).</p> <div class="h3" dir="ltr"><strong>Your Responsibilities</strong></div> <ul> <li dir="ltr"> <p dir="ltr">Develop software and product features as an<strong> individual contributor</strong> while also<strong> supporting the team</strong> on complex tasks</p> </li> <li dir="ltr"> <p dir="ltr"><strong>Clarify technical questions </strong>with colleagues and clients</p> </li> <li dir="ltr"> <p dir="ltr">Provide <strong>effort estimations </strong>and<strong> break down tasks</strong> into technical requirements and implementation details</p> </li> <li dir="ltr"> <p dir="ltr">Prepare and <strong>own technical and architectural decisions</strong></p> </li> <li dir="ltr"> <p dir="ltr"><strong>Research and analyze</strong> new technologies and methodologies</p> </li> <li dir="ltr"> <p dir="ltr"><strong>Onboard and train</strong> new and junior developers in the team</p> </li> <li dir="ltr"> <p dir="ltr"><strong>Remove blockers</strong> for colleagues by coordinating and leading meetings, helping to find answers and doing code reviews and pull requests</p> </li> <li dir="ltr"> <p dir="ltr">Take responsibility for <strong>process, documentation</strong> and <strong>code quality</strong></p> </li> <li dir="ltr"> <p dir="ltr">Implementation of <strong>Drupal</strong> modules and alteration of existing Drupal features</p> </li> <li dir="ltr"> <p dir="ltr">Patch modules if necessary and post patches on drupal.org</p> </li> <li dir="ltr"> <p dir="ltr">Test implementations with both <strong>manual and automated tests</strong> (Behat) as well as improve our testing infrastructure in collaboration with the testing engineer</p> </li> </ul> <div class="h3" dir="ltr"><strong>Skills &amp; Requirements</strong></div> <ul> <li dir="ltr"> <p dir="ltr">Technical education and at least <strong>5 years of relevant work experience </strong>as a Software Engineer or Software Architect</p> </li> <li dir="ltr"> <p dir="ltr">Proficient knowledge of<strong> PHP, MySQL</strong></p> </li> <li dir="ltr"> <p dir="ltr">A solid understanding of <strong>Drupal 7</strong> (Drupal 8/9 is a plus)</p> </li> <li dir="ltr"> <p dir="ltr">Optional technologies we work with that are a plus:<strong> React.js, Next.js, </strong>HTML5, CSS3, SASS, JavaScript, <strong>Apache Solr</strong></p> </li> <li dir="ltr"> <p dir="ltr">Ability to to work in <strong>cross-functional and remote teams</strong> to deliver on a common goal</p> </li> <li dir="ltr"> <p dir="ltr">Excellent<strong> analytical skills</strong></p> </li> <li dir="ltr"> <p dir="ltr">Good <strong>communication, prioritization </strong>and<strong> time management skills</strong>: You know when it’s time to cut back on individual contributions in order to unblock your colleagues</p> </li> <li dir="ltr"> <p dir="ltr">Excellent<strong> English skills (C1/C2)</strong>, German is a plus</p> </li> <li dir="ltr"> <p dir="ltr">Experience with<strong> SCRUM or agile software development</strong> is a plus</p> </li> <li dir="ltr"> <p dir="ltr"><strong>Leadership </strong>or mentoring experience is a plus</p> </li> </ul> <div class="h3" dir="ltr"><strong>More details &amp; Benefits</strong></div> <ul> <li dir="ltr"> <p dir="ltr"><strong>Start date: anytime</strong></p> </li> <li dir="ltr"> <p dir="ltr"><strong>Location:</strong> Vienna, Linz, Bratislava; hybrid models or fully remote (within Europe) also possible</p> </li> <li dir="ltr"> <p dir="ltr">The <strong>minimum salary</strong> for this role is in Austria governed by the collective agreement for IT Services and starts from 44.660,- € gross per year (full-time, 38,5 hrs/week.task group ST1, Standard Level)<strong>.</strong> The <strong>salary range for this role that we can offer is 46.000,- € to 56.000,- € gross per year </strong>(full-time position in Vienna, 14 salaries), depending on qualification, skills and relevant work experience.</p> </li> <li dir="ltr"> <p dir="ltr"><strong>Flexible working hours:</strong> preferred full-time (38,5 hrs/w), part-time possible as well (32 or 36 hrs/week)</p> </li> <li dir="ltr"> <p dir="ltr">High level of <strong>flexibility and autonomy</strong></p> </li> <li dir="ltr"> <p dir="ltr"><strong>Numerous company benefits</strong> e.g. Gym membership, regular team events and team lunches, annual company retreat, participation in the Company Bonus Programme (after the first year), free online psychological counseling and coaching via Instahelp, training and courses</p> </li> </ul> <img src="https://remotive.com/job/track/1288644/blank.gif?source=public_api" alt=""/>`
},
{
id: 1287327,
url: "https://remotive.com/remote-jobs/devops/site-reliability-engineer-1287327",
title: "Site Reliability Engineer",
company_name: "TableCheck",
company_logo: "https://remotive.com/job/1287327/logo",
category: "DevOps / Sysadmin",
tags: [
"amazon",
"AWS",
"developer",
"devops",
"go",
"javascript",
"kubernetes",
"python",
"ruby",
"scrum",
"SRE",
"management",
"agile",
"automation",
"elixir",
"rust",
"Engineering",
"documentation",
"CI/CD",
"languages",
"bash",
"web",
"English",
"gdpr",
"business",
"infrastructure",
"terraform",
"Site Reliability",
"chat",
"startup",
"IT",
"software engineering",
"communication",
"support",
"production",
"consul",
"Japanese",
"software"
],
job_type: "",
publication_date: "2022-07-03T19:39:21",
candidate_required_location: "",
salary: "",
description: `<p><strong>Job Description:</strong></p><p>TableCheck, Japan's leading restaurant reservation management platform, is seeking a Site Reliability Engineer. As a member of our SRE team you will own the technology stack and help support our demanding business and developer needs.</p><p>We run a robust and fault-tolerant infrastructure built on Amazon Web Services (AWS) with Terraform, Kubernetes, Helm, and an array of tools for CI/CD, logging, monitoring, and so on. We emphasize DevOps best practices such as agile, scrum, automation, and customer-centric improvements.</p><p>TableCheck has embraced remote work. As such, communication and documentation are in our blood. We look for and write about signals in the noise which enables us to constantly learn from mistakes and adapt, and we expect members of our teams to constantly follow up with questions and updates to keep everyone in the loop.</p><p><strong>Responsibilities include:</strong></p><p>・Following SRE principles to maintain a 24/7 production environment running on Kubernetes<br>・Implementation of DevOps methodologies to improve IT team quality of life<br>・Proactive system monitoring and configuration<br>・Incident response<br></p><p><strong>Mandatory Skills</strong></p><p> </p><p>・Must have at least 2 years experience with Amazon Web Services (AWS), with particular focus on EKS, EC2, RDS, Fargate, CloudFront, Lambda, and S3<br>・Must have extensive experience using AWS EKS<br>・Must have experience in direct software engineering following DevOps practices with at least 1 year as a technical lead<br>・Current ability in at least one of the following languages: Python, Ruby, Elixir, Go, Javascript, Rust<br>・Must understand container and hypervisor fundamentals<br>・Configuration management (YAML / Bash), experience with Helm and Terraform preferred<br>・Experience running production systems at large scale, and an understanding of the kinds of problems that can occur along with likely solutions</p><p> </p><p><strong>Recommended Skills</strong></p><p> </p><p>・Previous startup experience is highly desired<br>・Hashicorp stack (Terraform, Consul, Vault)<br>・ArgoCD<br>・Prometheus<br>・Grafana<br>・PostgreSQL<br>・MongoDB<br>・Kafka<br>・Security, PCI-DSS, GDPR, forensics, etc</p><p> </p><p><strong>Language Skills</strong></p><p> </p><p>・A native level of English is required.<br>(No Japanese skill is required for this role.)</p><p> </p><p><strong>Evaluation Criteria</strong></p><p> </p><p>We will evaluate candidates based on the following stages:<br>Initial interview - a one-on-one 30 minute chat over Google Meet to see if we're the right fit<br>Technical interview - (virtually) meet the SRE team at TableCheck to evaluate your skills (no whiteboard or materials required)<br>Take-home project - we will provide you with a 30-60 minute project, which will evaluate your dev and ops skills</p><p> </p><img src="https://remotive.com/job/track/1287327/blank.gif?source=public_api" alt=""/>`
},
{
id: 1290287,
url: "https://remotive.com/remote-jobs/software-dev/backend-software-engineer-1290287",
title: "Backend Software Engineer",
company_name: "top.legal",
company_logo: "https://remotive.com/job/1290287/logo",
category: "Software Development",
tags: [
"AWS",
"backend",
"contract",
"developer",
"docker",
"excel",
"javascript",
"legal",
"machine learning",
"saas",
"sales",
"salesforce",
"growth",
"ai",
"agile",
"automation",
"B2B",
"Engineering",
"product",
"product development",
"knowledge",
"data",
"Typescript ",
"English",
"business",
"development",
"hubspot",
"learning",
"serverless",
"data-driven",
"microservices",
"stripe",
"jest",
"software"
],
job_type: "full_time",
publication_date: "2022-07-03T13:39:33",
candidate_required_location: "Germany",
salary: "",
description: `<p><br><br></p> <div class="h3">Company Description</div> <p>We at top.legal create more <strong>valuable business relationships</strong>. Specifically, we help companies to interact more valuably and meaningfully with their customers through data-driven contracting. We have developed an AI-enabled SaaS-Contract technology that combines sales enablement with legal automation to close more valuable deals faster. </p> <p>Our team is made-up by an experienced team of tech-enthusiasts as well as hacking geniuses, who have already successfully built several companies. Right now is an exciting time to join a team that is applying machine learning and cutting-edge microservices to further its development. </p> <p>We are currently looking for you as a <strong>backend software engineer </strong>in Munich or remotely to become part of our pioneering work. Together we want to create more valuable and efficient contracting processes in a customer-centric manner. Exciting challenges, start-up experience and a great team are waiting for you.</p> <p><br><br></p> <div class="h3">Job Description</div> <p>As a backend developer within the top.legal’s integrate squad you help to develop a state-of-the-art B2B SaaS product in an agile remote product &amp; engineering team</p> <p>Required hard skills or willingness to learn:</p> <ul> <li> <p>AWS serverless framework</p> </li> <li> <p>AWS dynamodb, sqs, lambda, appsync.</p> </li> <li> <p>Typescript/Javascript </p> </li> <li> <p>Jest</p> </li> <li> <p>Docker</p> </li> <li> <p> Integrating our solution with: Salesforce, Hubspot, Stripe, etc.</p> </li> <li> <p>Strong knowledge of *nixOS</p> </li> <li> <p>You know how to focus <strong>110% on customer impact and be 100% committed to the team</strong>. We are A-players and we enjoy to work with A-players. </p> </li> </ul> <ul> <li> <p>You are part of a customer-driven, sprint-based product development process and break down complex tasks into deliverable output (feasibility assessment, shippable feature etc.)</p> </li> </ul> <p><br><br></p> <div class="h3">Qualifications</div> <p>Is this you?</p> <p>top.legal <strong>unlocks</strong> <strong>value in business relationships</strong>. As a team-member you propel this vision forward by being: </p> <ul> <li> <p><strong>ENTREPRENEURIAL</strong>: You take ownership and burn to have impact. You have a bias-to-action and interpret challenges as opportunities to grow and shape the future. You take risks, because only those who dare create something groundbreaking. </p> </li> <li> <p><strong>VALUABLE</strong>: You strive to be valuable to our team through full commitment so that we can bring value to our customers. Our customer manage the value of their relationships through our software. Being valuable starts with ourselves. We are builders who solve problems for our customers. </p> </li> </ul> <ul> <li> <p><strong>EMPATHETIC</strong>: You have a very strong curiosity to learn, especially a willingness to understand the customer’s perspective. You communicate with anticipation of the other - especially in a remote team where reliability and proactive are especially important.</p> </li> </ul> <p><strong>Requirements</strong></p> <ul> <li> <p>You excel at working remotely (proactive, reliable through commitment, driven by empathy, be fun and stay human).</p> </li> <li> <p>Our multicultural team requires a professional English proficiency.</p> </li> </ul> <p><br><br></p> <div class="h3">Additional Information</div> <p><strong>Perks</strong></p> <ul> <li> <p>You work on an incredibly exciting project in which you can push your own boundary and grow.</p> </li> <li> <p>You will be able to apply and hone your ability and align your personal growth with our fast-growing success story.</p> </li> <li> <p>You join one of Germany's most promising startups, financed by Germany's most renowned investors. </p> </li> <li> <p>You will get 20 days of vacation after your probation period.</p> </li> <li> <p>We offer flexible working hours, because we are result-driven.</p> </li> <li> <p>We pay in dollars or euros.</p> </li> </ul> <img src="https://remotive.com/job/track/1290287/blank.gif?source=public_api" alt=""/>`
},
{
id: 1285162,
url: "https://remotive.com/remote-jobs/writing/technical-writer-1285162",
title: "Technical Writer",
company_name: "Rarify",
company_logo: "https://remotive.com/job/1285162/logo",
category: "Writing",
tags: [
"api",
"developer",
"golang",
"javascript",
"design",
"programming",
"content",
"research",
"Engineering",
"documentation",
"product",
"languages",
"markdown",
"APIs",
"technical documentation",
"writing",
"JSON",
"integrations",
"OpenAPI",
"software"
],
job_type: "full_time",
publication_date: "2022-07-02T21:40:09",
candidate_required_location: "Worldwide",
salary: "",
description: `<p>As a technical writer at Rarify, you’ll provide clear information about how developers can integrate with our API and other tools. This content includes API reference documentation, user-focused guides, tutorials, and other materials to cover our growing platform's newest features.</p> <p>You'll work closely with our product, engineering, and design teams as we create a superior developer experience for our customers. As we grow, you'll get the benefit of our research into our customers' needs and the opportunity to help shape our developer offerings into a usable, clearly-documented platform. You'll expand our developer portal, set standards for our information, and may eventually manage other writers.</p> <div class="h4">What you’ll do</div> <ul> <li>Document new APIs, features, and improvements, written in a mix of markdown &amp; JSON</li> <li>With the help of our design and engineering team, expand our developer platform and its technical documentation</li> <li>Create guidelines, tutorials and document best practices for engineers</li> <li>Collect and resolve documentation feedback</li> </ul> <ul> <li>3+ years of writing documentation for developer-focused software</li> <li>Experience with OpenAPI documentation</li> <li>Strong writing and editorial skills</li> <li>Programming skills in languages such as JavaScript and Golang</li> <li>Proficiency in Markdown-based docs-like-code documentation</li> </ul> <div class="h4">Bonus points for:</div> <ul> <li>Living in [-5, +5] time zones</li> <li>Experience building API platforms, developer portals, or integrations between third party platforms</li> </ul> <img src="https://remotive.com/job/track/1285162/blank.gif?source=public_api" alt=""/>`
}
]